/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LearnersRouteImport } from './routes/learners'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'

const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersRoute = LearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/fleet': typeof FleetRoute
  '/learners': typeof LearnersRoute
  '/notifications': typeof NotificationsRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/fleet': typeof FleetRoute
  '/learners': typeof LearnersRoute
  '/notifications': typeof NotificationsRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/fleet': typeof FleetRoute
  '/learners': typeof LearnersRoute
  '/notifications': typeof NotificationsRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/fleet'
    | '/learners'
    | '/notifications'
    | '/revenue'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookings' | '/fleet' | '/learners' | '/notifications' | '/revenue'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/fleet'
    | '/learners'
    | '/notifications'
    | '/revenue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  FleetRoute: typeof FleetRoute
  LearnersRoute: typeof LearnersRoute
  NotificationsRoute: typeof NotificationsRoute
  RevenueRoute: typeof RevenueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners': {
      id: '/learners'
      path: '/learners'
      fullPath: '/learners'
      preLoaderRoute: typeof LearnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  FleetRoute: FleetRoute,
  LearnersRoute: LearnersRoute,
  NotificationsRoute: NotificationsRoute,
  RevenueRoute: RevenueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
