/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnersRouteImport } from './routes/learners'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as IndexRouteImport } from './routes/index'

const LearnersRoute = LearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fleet': typeof FleetRoute
  '/learners': typeof LearnersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fleet': typeof FleetRoute
  '/learners': typeof LearnersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fleet': typeof FleetRoute
  '/learners': typeof LearnersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fleet' | '/learners'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fleet' | '/learners'
  id: '__root__' | '/' | '/fleet' | '/learners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FleetRoute: typeof FleetRoute
  LearnersRoute: typeof LearnersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learners': {
      id: '/learners'
      path: '/learners'
      fullPath: '/learners'
      preLoaderRoute: typeof LearnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FleetRoute: FleetRoute,
  LearnersRoute: LearnersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
